name: flutter_webview_plugin_ios_android
description: Plugin that allow Flutter to communicate with a native Webview and keeps .

homepage: https://github.com/ec-siddhant/flutter_webview_plugin_ios
version: 0.3.12+11
maintainer: Siddhant Parashar

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.10.0"

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterWebviewPlugin
      android:
        package: com.flutter_webview_plugin
        pluginClass: FlutterWebviewPlugin

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^9.0.2


dev_dependencies:
  mockito: ^5.2.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter